CREATE DATABASE IF NOT EXISTS produccion;
USE produccion;

CREATE TABLE IF NOT EXISTS pais (
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS departamento(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  IdPaisFk INT(11) NOT NULL,
  FOREIGN KEY (IdPaisFk) REFERENCES pais(Id)
);

CREATE TABLE IF NOT EXISTS municipio(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  IdDepartamentoFK INT(11) NOT NULL,
  FOREIGN KEY (IdDepartamentoFk) REFERENCES departamento(Id)
);

CREATE TABLE IF NOT EXISTS empresa(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nit VARCHAR(50) NOT NULL,
  razon_social TEXT NOT NULL,
  representante_legal VARCHAR(50) NOT NULL,
  FechaCreacion DATE NOT NULL,
  IdMunicipioFk INT(11) NOT NULL,
  FOREIGN KEY (IdMunicipioFk) REFERENCES municipio(Id)
);

CREATE TABLE IF NOT EXISTS tipo_persona(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS proveedor(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NitProveedor VARCHAR(50) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  IdTipoPersona INT(11) NOT NULL,
  IdMunicipioFk INT(11) NOT NULL,
  FOREIGN KEY (IdTipoPersona) REFERENCES tipo_persona(Id),
  FOREIGN KEY (IdMunicipioFk) REFERENCES municipio(Id)
);

CREATE TABLE IF NOT EXISTS cliente(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  IdCliente VARCHAR(50) NOT NULL,
  IdTipoPersonaFk INT(11) NOT NULL,
  fechaRegistro DATE NOT NULL,
  IdMunicipioFk INT(11) NOT NULL,
  FOREIGN KEY (IdTipoPersonaFK) REFERENCES tipo_persona(Id),
  FOREIGN KEY (IdMunicipioFk) REFERENCES municipio(Id)
);

CREATE TABLE IF NOT EXISTS cargos(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  descripcion VARCHAR(50) NOT NULL,
  sueldo_base DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS empleado(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  IdCargoFk INT(11) NOT NULL,
  fecha_ingreso DATE NOT NULL,
  IdMunicipioFk INT(11) NOT NULL,
  FOREIGN KEY (IdCargoFK) REFERENCES cargos(Id),
  FOREIGN KEY (IdMunicipioFk) REFERENCES municipio(Id)
);

CREATE TABLE IF NOT EXISTS forma_pago(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS venta(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Fecha DATE NOT NULL,
  IdEmpleadoFk INT(11) NOT NULL,
  IdClienteFk INT(11) NOT NULL,
  IdFormaPagoFk INT(11) NOT NULL,
  FOREIGN KEY (IdEmpleadoFk) REFERENCES empleado(Id),
  FOREIGN KEY (IdClienteFk) REFERENCES cliente(Id),
  FOREIGN KEY (IdFormaPagoFk) REFERENCES forma_pago(Id)
);

CREATE TABLE IF NOT EXISTS tipo_estado(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS estado(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  descripcion VARCHAR(50) NOT NULL,
  IdTipoEstadoFk INT(11) NOT NULL,
  FOREIGN KEY (IdTipoEstadoFk) REFERENCES tipo_estado(Id)
);

CREATE TABLE IF NOT EXISTS orden(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  fecha DATE NOT NULL,
  IdEmpleadoFk INT(11) NOT NULL,
  IdCLienteFk INT(11) NOT NULL,
  IdEstadoFk INT(11) NOT NULL,
  FOREIGN KEY (IdEmpleadoFk) REFERENCES empleado(Id),
  FOREIGN KEY (IdClienteFk) REFERENCES cliente(Id),
  FOREIGN KEY (IdEstadoFk) REFERENCES estado(Id)
);

CREATE TABLE IF NOT EXISTS insumo(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  valor_unit DOUBLE NOT NULL,
  stock_min DOUBLE NOT NULL,
  stock_max DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS insumo_proveedor(
  IdInsumoFk INT(11) NOT NULL,
  IdProveedorFk INT(11) NOT NULL,
  FOREIGN KEY (IdInsumoFk) REFERENCES insumo(Id),
  FOREIGN KEY (IdProveedorFk) REFERENCES proveedor(Id)
);

CREATE TABLE IF NOT EXISTS color(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Descripcion VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tipo_proteccion(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS genero(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS prenda(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(50) NOT NULL,
  ValorUnitCop DOUBLE NOT NULL,
  ValorUnitUsd DOUBLE NOT NULL,
  IdEstadoFk INT(11) NOT NULL,
  IdTipoProteccion INT(11) NOT NULL,
  IdGeneroFk INT(11) NOT NULL,
  Codigo VARCHAR(50) NOT NULL,
  FOREIGN KEY (IdEstadoFk) REFERENCES estado(Id),
  FOREIGN KEY (IdTipoProteccion) REFERENCES tipo_proteccion(Id),
  FOREIGN KEY (IdGeneroFk) REFERENCES genero(Id)
);

CREATE TABLE IF NOT EXISTS detalle_orden(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  IdOrdenFk INT(11) NOT NULL,
  IdPrendaFk INT(11) NOT NULL,
  cantidad_producir INT(11) NOT NULL,
  IdColorFk INT(11) NOT NULL,
  cantidad_producida INT(11) NOT NULL,
  IdEstadoFk INT(11) NOT NULL,
  FOREIGN KEY (IdOrdenFk) REFERENCES orden(Id),
  FOREIGN KEY (IdPrendaFk) REFERENCES prenda(Id),
  FOREIGN KEY (IdColorFk) REFERENCES color(Id),
  FOREIGN KEY (IdEstadoFk) REFERENCES estado(Id)
);

CREATE TABLE IF NOT EXISTS insumo_prendas(
  IdInsumoFk INT(11) NOT NULL,
  IdPrendaFk INT(11) NOT NULL,
  Cantidad INT(11) NOT NULL,
  FOREIGN KEY (IdInsumoFk) REFERENCES insumo(Id),
  FOREIGN KEY (IdPrendaFk) REFERENCES prenda(Id)
);

CREATE TABLE IF NOT EXISTS inventario(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CodInv VARCHAR(255) NOT NULL,
  IdPrendaFk INT(11) NOT NULL,
  ValorVtaCop DOUBLE NOT NULL,
  ValorVtaUsd DOUBLE NOT NULL,
  FOREIGN KEY (IdPrendaFk) REFERENCES prenda(Id)
);

CREATE TABLE IF NOT EXISTS talla(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS inventario_talla(
  IdInvFk INT(11) NOT NULL,
  IdTallaFk INT(11) NOT NULL,
  FOREIGN KEY (IdInvFk) REFERENCES inventario(Id),
  FOREIGN KEY (IdTallaFk) REFERENCES talla(Id)
);

CREATE TABLE IF NOT EXISTS detalle_venta(
  Id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  IdVentaFk INT(11) NOT NULL,
  IdProductoFk INT(11) NOT NULL,
  IdTallaFk INT(11) NOT NULL,
  cantidad INT(11) NOT NULL,
  valor_unit DOUBLE NOT NULL,
  FOREIGN KEY (IdVentaFk) REFERENCES venta(Id),
  FOREIGN KEY (IdProductoFk) REFERENCES inventario(Id),
  FOREIGN KEY (IdTallaFk) REFERENCES talla(Id)
);
